require("config.lazy")
require('options')
require('mappings')
require('autocommands')
require('theme')

require('plugins.telescope')
require('plugins.oil')
require('plugins.trouble')
require('plugins.gitsigns')
require('plugins.undotree')
