vim.cmd "hi clear"
if vim.fn.exists "syntax_on" then
  vim.cmd "syntax reset"
end
vim.o.termguicolors = true
vim.g.colors_name = "gerry-dark"

local c = require "gerry-dark.palette"

local hl = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hl("Normal", { fg = c.fg, bg = c.bg })
hl("NormalNC", { fg = c.fg, bg = c.bg })
hl("NormalFloat", { fg = c.fg, bg = c.bg_float })
hl("FloatBorder", { fg = c.accent, bg = c.bg_float })
hl("FloatTitle", { fg = c.fg, bg = c.bg_float, bold = true })
hl("SignColumn", { bg = c.bg })
hl("LineNr", { fg = c.dim })
hl("CursorLineNr", { fg = c.blue, bold = true })
hl("CursorLine", { bg = c.hover_bg })
hl("Cursor", { fg = c.bg, bg = c.caret })
hl("lCursor", { link = "Cursor" })
hl("CursorColumn", { bg = c.bg_highlight })
hl("ColorColumn", { bg = c.bg_highlight })
hl("Visual", { bg = c.bg_visual })
hl("VisualNOS", { bg = c.bg_visual })
hl("Search", { bg = c.bg_search, fg = c.fg })
hl("IncSearch", { bg = c.accent, fg = c.bg, bold = true })
hl("CurSearch", { bg = c.accent, fg = c.bg, bold = true })
hl("Substitute", { bg = c.red, fg = c.bg })
hl("MatchParen", { bg = c.matched, bold = true })
hl("Pmenu", { fg = c.fg, bg = c.bg_float })
hl("PmenuSel", { fg = c.sel_fg, bg = c.sel_bg })
hl("PmenuSbar", { bg = c.bg_float })
hl("PmenuThumb", { bg = c.border })
hl("WinSeparator", { fg = c.border })
hl("VertSplit", { fg = c.border })
hl("StatusLine", { fg = c.fg, bg = c.bg_statusline })
hl("StatusLineNC", { fg = c.fg_dark, bg = c.bg_statusline })
hl("WinBar", { fg = c.fg, bg = c.bg_statusline })
hl("WinBarNC", { fg = c.fg_dark, bg = c.bg_statusline })
hl("TabLine", { fg = c.fg_dark, bg = c.bg_statusline })
hl("TabLineFill", { bg = c.bg_statusline })
hl("TabLineSel", { fg = c.fg, bg = c.bg })
hl("Title", { fg = c.green, bold = true })
hl("Directory", { fg = c.blue })
hl("ErrorMsg", { fg = c.red })
hl("WarningMsg", { fg = c.amber })
hl("ModeMsg", { fg = c.fg })
hl("MoreMsg", { fg = c.green })
hl("Question", { fg = c.green })
hl("NonText", { fg = c.whitespace })
hl("EndOfBuffer", { fg = c.bg_dark })
hl("SpecialKey", { fg = c.whitespace })
hl("Whitespace", { fg = c.whitespace })
hl("Folded", { fg = c.fg_dark, bg = c.folded })
hl("FoldColumn", { fg = c.fg_dark, bg = c.bg })

hl("Comment", { fg = c.comment, italic = true })
hl("Constant", { fg = c.green })
hl("String", { fg = c.green })
hl("Character", { fg = c.green })
hl("Number", { fg = c.cyan })
hl("Boolean", { fg = c.green })
hl("Float", { fg = c.cyan })
hl("Identifier", { fg = c.fg })
hl("Function", { fg = c.orange })
hl("Statement", { fg = c.purple })
hl("Conditional", { fg = c.purple })
hl("Repeat", { fg = c.purple })
hl("Label", { fg = c.purple })
hl("Operator", { fg = c.purple })
hl("Keyword", { fg = c.purple })
hl("Exception", { fg = c.purple })
hl("PreProc", { fg = c.purple })
hl("Include", { fg = c.purple })
hl("Define", { fg = c.purple })
hl("Macro", { fg = c.purple })
hl("PreCondit", { fg = c.purple })
hl("Type", { fg = c.salmon })
hl("StorageClass", { fg = c.salmon })
hl("Structure", { fg = c.salmon })
hl("Typedef", { fg = c.salmon })
hl("Special", { fg = c.orange })
hl("SpecialChar", { fg = c.orange })
hl("Tag", { fg = c.salmon })
hl("Delimiter", { fg = c.fg })
hl("SpecialComment", { fg = c.comment, italic = true })
hl("Debug", { fg = c.red })
hl("Underlined", { fg = c.blue, underline = true })
hl("Ignore", { fg = c.fg_dark })
hl("Error", { fg = c.red })
hl("Todo", { fg = c.bg, bg = c.amber, bold = true })

hl("DiffAdd", { bg = "#263B2D" })
hl("DiffChange", { bg = "#253847" })
hl("DiffDelete", { bg = "#303744" })
hl("DiffText", { bg = "#2B4768" })

hl("DiagnosticError", { fg = c.red })
hl("DiagnosticWarn", { fg = c.amber })
hl("DiagnosticInfo", { fg = c.blue })
hl("DiagnosticHint", { fg = c.green })
hl("DiagnosticUnderlineError", { sp = c.red, underline = true })
hl("DiagnosticUnderlineWarn", { sp = c.amber, underline = true })
hl("DiagnosticUnderlineInfo", { sp = c.blue, underline = true })
hl("DiagnosticUnderlineHint", { sp = c.green, underline = true })
hl("DiagnosticVirtualTextError", { fg = c.red })
hl("DiagnosticVirtualTextWarn", { fg = c.amber })
hl("DiagnosticVirtualTextInfo", { fg = c.blue })
hl("DiagnosticVirtualTextHint", { fg = c.green })

hl("@comment", { link = "Comment" })
hl("@string", { link = "String" })
hl("@number", { link = "Number" })
hl("@boolean", { link = "Boolean" })
hl("@function", { link = "Function" })
hl("@function.builtin", { fg = c.orange })
hl("@function.call", { fg = c.orange })
hl("@method", { fg = c.orange })
hl("@method.call", { fg = c.orange })
hl("@function.method", { link = "Function" })
hl("@function.method.call", { link = "Function" })
hl("@constructor", { fg = c.salmon })
hl("@keyword", { link = "Keyword" })
hl("@keyword.function", { fg = c.purple })
hl("@keyword.return", { fg = c.purple })
hl("@keyword.operator", { fg = c.purple })
hl("@conditional", { link = "Conditional" })
hl("@repeat", { link = "Repeat" })
hl("@variable", { fg = c.fg })
hl("@variable.builtin", { fg = c.salmon })
hl("@variable.parameter", { fg = c.blue })
hl("@parameter", { fg = c.blue })
hl("@property", { fg = c.salmon })
hl("@field", { fg = c.salmon })
hl("@variable.member", { fg = c.salmon })
hl("@attribute", { fg = c.orange })
hl("@constant", { link = "Constant" })
hl("@constant.builtin", { fg = c.green })
hl("@type", { link = "Type" })
hl("@type.builtin", { fg = c.salmon })
hl("@tag", { fg = c.salmon })
hl("@tag.attribute", { fg = c.orange })
hl("@tag.delimiter", { fg = c.purple })
hl("@punctuation.delimiter", { fg = c.fg })
hl("@punctuation.bracket", { fg = c.fg })
hl("@punctuation.special", { fg = c.purple })
hl("@operator", { link = "Operator" })
hl("@namespace", { fg = c.green })
hl("@module", { fg = c.green })
hl("@include", { link = "Include" })
hl("@text.title", { fg = c.green, bold = true })
hl("@text.bold", { fg = c.green, bold = true })
hl("@text.italic", { fg = c.green, italic = true })
hl("@text.underline", { fg = c.blue, underline = true })
hl("@text.literal", { fg = c.green })
hl("@text.uri", { fg = c.blue, underline = true })

hl("LspReferenceText", { bg = c.identifier })
hl("LspReferenceRead", { bg = c.identifier })
hl("LspReferenceWrite", { bg = c.identifier })
hl("LspInlayHint", { fg = c.hint_fg, bg = c.hint_bg })

hl("GitSignsAdd", { fg = c.green })
hl("GitSignsChange", { fg = c.blue })
hl("GitSignsDelete", { fg = c.red })

hl("TelescopeNormal", { fg = c.fg, bg = c.bg })
hl("TelescopeBorder", { fg = c.border, bg = c.bg })
hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg })
hl("TelescopePromptBorder", { fg = c.blue, bg = c.bg })
hl("TelescopeResultsBorder", { fg = c.border, bg = c.bg })
hl("TelescopePreviewBorder", { fg = c.border, bg = c.bg })
hl("TelescopePromptTitle", { fg = c.accent, bg = c.bg, bold = true })
hl("TelescopeResultsTitle", { fg = c.blue, bg = c.bg, bold = true })
hl("TelescopePreviewTitle", { fg = c.green, bg = c.bg, bold = true })
hl("TelescopeSelection", { fg = c.hover_fg, bg = c.hover_bg })
hl("TelescopeSelectionCaret", { fg = c.hover_fg, bg = c.hover_bg, bold = true })
hl("TelescopeMatching", { fg = c.blue, bold = true })

hl("OilNormalFloat", { fg = c.fg, bg = c.bg })
hl("OilFloatBorder", { fg = c.blue, bg = c.bg })
hl("OilCursorLine", { bg = c.hover_bg })

hl("WhichKey", { fg = c.orange })
hl("WhichKeyGroup", { fg = c.blue })
hl("WhichKeyDesc", { fg = c.fg })
hl("WhichKeySeparator", { fg = c.fg_dark })

hl("WinBarIsland", { fg = c.fg, bg = c.bg_float })
hl("WinBarIslandIcon", { fg = c.blue, bg = c.bg_float })
hl("WinBarIslandSep", { fg = c.fg_dark, bg = c.bg_float })
